# Generated by Django 5.2.2 on 2025-06-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
